/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parekhtdd;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
         //Setup
         Cart cart = new Cart();
         Item item1 = new Item("Book",200,false);
         Item item2 = new Item("Shoes",100,false);
         //Execute
         cart.addItem(item1, 2);
         cart.addItem(item2, 5);
         int quantity = cart.QuantityOfCart();
         System.out.println(quantity);
    }
}
