/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parekhtdd;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
         //Setup
         Cart cart = new Cart();
         Item item = new Item("Book",300,false);
         //Execute
         cart.addItem(item, 2);
         int sum = cart.SumOfCart();
         System.out.println(sum);
    }
}
