/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parekhtdd;

import org.junit.Test;
import static org.junit.Assert.*;


public class AppTest {
    //Given that I a new shopper, when I begin shopping, then I expect my cart to be empty.
    @Test
     public void EmptyCartOnFirstTime(){
        //Setup
        Cart cart = new Cart();
        //Execute
        int size = cart.getItems().size();
        //Assert
        assertEquals(0,size);
    }

    // Given I have an empty cart, when I add an Item, then I expect to the price reflect the sum of all the Items in my cart.
    @Test
    public void ChangeSumAfterAddingItem(){
        //Setup
        Cart cart = new Cart();
        Item item = new Item("Book",200,false);
        //Execute
        cart.addItem(item, 2);
        int sum = cart.SumOfCart();
        //Assert
        assertEquals(400,sum);
    }

    // Given I have cart with one item, when I add more of that item, then I expect to see its quantity update on the cart.
    @Test
    public void UpdateQuantityAfterAddingItem(){
        //Setup
        Cart cart = new Cart();
        Item item1 = new Item("Book",200,false);
        Item item2 = new Item("Shoes",100,false);
        //Execute
        cart.addItem(item1, 2);
        cart.addItem(item2, 5);
        int quantity = cart.QuantityOfCart();
        //Assert
        assertEquals(7, quantity);
    }
}
