/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parekhtdd;

import org.junit.Test;
import static org.junit.Assert.*;


public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    //Given that I a new shopper, when I begin shopping, then I expect my cart to be empty.
    @Test
     public void EmptyCartOnFirstTime(){
        //Setup
        Cart cart = new Cart();
        //Execute
        int size = cart.getItems().size();
        //Assert
        assertEquals(0,size);
    }

    // Given I have an empty cart, when I add an Item, then I expect to the price reflect the sum of all the Items in my cart.
    @Test
    public void ChangeSumAfterAddingItem(){
        //Setup
        Cart cart = new Cart();
        Item item = new Item("Book",200,false);
        //Execute
        cart.addItem(item, 2);
        int sum = cart.SumOfCart();
        //Assert
        assertEquals(400,sum);
    }
}
